name:  Propozycja funkcji
description: Zaproponuj now funkcj dla Sokratesa
title: "[FEATURE] "
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Dzikuj za propozycj! Nowe pomysy pomagaj rozwija Sokratesa.

  - type: textarea
    id: feature-description
    attributes:
      label: Opis funkcji
      description: Opisz dokadnie jak funkcj chciaby doda
      placeholder: |
        Przykad: Chciabym, 偶eby Sokrates m贸g uczy r贸wnie偶 jzyk贸w obcych. 
        U偶ytkownik m贸gby wybra jzyk (angielski, niemiecki, francuski) i Sokrates 
        zadawaby pytania w tym jzyku, pomagajc w nauce.
    validations:
      required: true

  - type: textarea
    id: problem-solved
    attributes:
      label: Jaki problem to rozwizuje?
      description: Opisz dlaczego ta funkcja jest potrzebna
      placeholder: |
        Obecnie Sokrates uczy tylko w jzyku polskim, ale wielu u偶ytkownik贸w 
        chciaoby uczy si przedmiot贸w w jzykach obcych...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proponowane rozwizanie
      description: Jak widzisz implementacj tej funkcji?
      placeholder: |
        1. Dodanie wyboru jzyka na ekranie logowania
        2. Modyfikacja prompt贸w AI dla r贸偶nych jzyk贸w
        3. Wielojzyczne FAQ i interfejs
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatywne rozwizania
      description: Czy rozwa偶ae inne sposoby rozwizania tego problemu?
      placeholder: Mo偶na by te偶...

  - type: dropdown
    id: priority
    attributes:
      label: Priorytet
      description: Jak wa偶na jest ta funkcja?
      options:
        - "Mio mie (Nice to have)"
        - "redni priorytet"
        - "Wysoki priorytet" 
        - "Krytyczna funkcja"
    validations:
      required: true

  - type: dropdown
    id: difficulty
    attributes:
      label: Szacunkowa trudno implementacji
      description: Jak trudna wydaje Ci si implementacja?
      options:
        - "Nie wiem"
        - "atwa (kilka godzin)"
        - "rednia (kilka dni)"
        - "Trudna (kilka tygodni)"
        - "Bardzo trudna (miesice)"

  - type: textarea
    id: additional-context
    attributes:
      label: Dodatkowy kontekst
      description: Czy masz jakie dodatkowe informacje, linki, przykady?
      placeholder: |
        - Podobne rozwizania w innych aplikacjach
        - Linki do dokumentacji
        - Mockupy interfejsu

  - type: checkboxes
    id: terms
    attributes:
      label: Sprawdziem
      description: Przed zgoszeniem upewnij si, 偶e
      options:
        - label: Przeszukaem istniejce issues czy ta funkcja ju偶 nie zostaa zaproponowana
          required: true
        - label: Ta funkcja pasuje do filozofii Sokratesa (metoda sokratejska)
          required: true
        - label: Jestem got贸w pom贸c w testowaniu tej funkcji
          required: false
